on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Docker Build & Scan"]
    types:
      - completed

env:
  AWS_REGION: eu-north-1  

jobs:
  terraform:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: terraform

      - name: Install and Run TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --version
          tflint --init --chdir=terraform
          tflint --chdir=terraform
          tflint --chdir=terraform --disable-rule=terraform_typed_variables --disable-rule=terraform_unused_declarations

      - name: Create terraform.tfvars from secret
        run: |
          mkdir -p terraform
          cat <<EOF > terraform/terraform.tfvars
${{ secrets.TF_VARS }}
EOF

      - name: Verify tfvars
        run: |
          test -s terraform/terraform.tfvars || (echo "TF_VARS secret is empty!" && exit 1)
          echo "TFVARS content:"
          cat terraform/terraform.tfvars

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: |
          terraform plan -var-file=terraform.tfvars -out=plan.out
          terraform show -no-color plan.out > plan.txt
        working-directory: terraform

      - name: Upload Plan Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan
          path: |
            terraform/plan.out
            terraform/plan.txt

      - name: Show Plan in Summary
        working-directory: terraform
        run: |
          {
            echo '## Terraform Plan'
            echo
            echo '```'
            sed -n '1,400p' plan.txt
            echo '```'
            echo
            echo '_Full plan attached as artifact (tf-plan)._'
          } >> "$GITHUB_STEP_SUMMARY"
